name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  days: # change this
    required: true
    description: 'number of days to include into the report'
    default: 7
runs:
  using: 'node16'
  main: 'dist/index.js'
